# Generated by Django 3.2.23 on 2024-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=45)),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
