# Generated by Django 3.2.23 on 2024-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('camp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('details', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'camp',
                'managed': True,
            },
        ),
    ]
